use-grammars = { only = ["clapse"] }

[[language]]
name = "clapse"
scope = "source.clapse"
file-types = ["clapse"]
comment-token = "--"
language-servers = ["clapse"]
grammar = "clapse"
roots = ["clapse.cabal"]
formatter = { command = "/home/mewhhaha/src/clapse/artifacts/bin/clapse", args = ["format", "--stdin"] }

[[grammar]]
name = "clapse"
source = { path = "/home/mewhhaha/src/clapse/tree-sitter-clapse" }

[language-server.clapse]
command = "/home/mewhhaha/src/clapse/artifacts/bin/clapse"
args = ["lsp", "--stdio"]
